# src/semantic_alignment/words.py

WORDS = [
    "pure mathematics",
    "applied mathematics",
    "statistics and probability",
    "computer sciences information science bioinformatics",
    "atomic molecular and chemical physics",
    "condensed matter physics",
    "particles and field physics",
    "nuclear physics",
    "fluids and plasma physics",
    "optics",
    "acoustics",
    "astronomy",
    "organic chemistry",
    "inorganic and nuclear chemistry",
    "physical chemistry",
    "polymer science",
    "electrochemistry",
    "analytical chemistry",
    "hydrology",
    "oceanography",
    "water resources",
    "mineralogy",
    "geology",
    "paleontology",
    "volcanology",
    "physical geography",
    "meteorology and atmospheric sciences",
    "climatic research",
    "environmental sciences",
    "cell biology",
    "biology evolutionary biology",
    "genetics and heredity",
    "reproductive biology",
    "developmental biology",
    "microbiology",
    "virology",
    "biochemistry and molecular biology",
    "biochemical research methods",
    "biophysics",
    "plant sciences botany",
    "mycology",
    "zoology",
    "behavioral sciences biology",
    "ornithology",
    "entomology",
    "marine biology freshwater biology limnology",
    "ecology",
    "biodiversity conservation",
    "other biological topics",
    "civil engineering",
    "construction engineering municipal and structural engineering",
    "architecture engineering",
    "transport engineering",
    "electrical and electronic engineering",
    "communication engineering and systems",
    "telecommunications",
    "robotics and automatic control",
    "automation and control systems",
    "computer hardware and architecture",
    "mechanical engineering",
    "applied mechanics",
    "thermodynamics",
    "aerospace engineering",
    "nuclear related engineering",
    "audio engineering reliability analysis",
    "chemical engineering",
    "chemical process engineering",
    "materials engineering",
    "paper and wood",
    "textiles",
    "ceramics",
    "composites",
    "coating and films",
    "medical engineering",
    "medical laboratory technology",
    "environmental and geological engineering geotechnics",
    "petroleum engineering",
    "mining and mineral processing",
    "energy and fuels",
    "remote sensing",
    "marine engineering sea vessels",
    "ocean engineering",
    "environmental biotechnology",
    "bioremediation diagnostic biotechnologies in environmental management",
    "environmental biotechnology related ethics",
    "industrial biotechnology",
    "bioprocessing technologies",
    "bioproducts",
    "nano materials",
    "nano processes",
    "food and beverages",
    "human genetics",
    "immunology",
    "neurosciences",
    "pharmacology and pharmacy",
    "physiology",
    "anatomy and morphology",
    "medicinal chemistry",
    "toxicology",
    "pathology",
    "cardiac and cardiovascular systems",
    "endocrinology and metabolism",
    "respiratory systems",
    "oncology",
    "hematology",
    "otorhinolaryngology",
    "ophthalmology",
    "dentistry oral surgery and medicine",
    "paediatrics",
    "clinical neurology",
    "orthopaedics",
    "surgery",
    "transplantation",
    "obstetrics and gynaecology",
    "psychiatry",
    "dermatology and venereal diseases",
    "urology and nephrology",
    "general and internal medicine",
    "gastroenterology and hepatology",
    "andrology",
    "critical care medicine and emergency medicine",
    "anaesthesiology",
    "radiology nuclear medicine and medical imaging",
    "allergy",
    "rheumatology",
    "geriatrics and gerontology",
    "integrative and complementary medicine",
    "other clinical medicine subjects",
    "social biomedical sciences",
    "epidemiology",
    "infectious diseases",
    "public and environmental health",
    "occupational health",
    "sport and fitness sciences",
    "nursing",
    "nutrition dietetics",
    "tropical medicine",
    "parasitology",
    "medical ethics",
    "substance abuse",
    "health related biotechnology",
    "technologies involving the manipulation of cells tissues organs or the whole organism",
    "technologies involving identifying the functioning of dna proteins and enzymes",
    "biomaterials",
    "medical biotechnology related ethics",
    "forensic science",
    "other medical science",
    "agriculture",
    "forestry",
    "fishery",
    "soil science",
    "horticulture viticulture",
    "agronomy plant breeding and plant protection",
    "animal and dairy science",
    "pets",
    "husbandry",
    "veterinary science",
    "agricultural biotechnology and food biotechnology",
    "gm technology",
    "agricultural biotechnology related ethics",
    "psychology",
    "special psychology",
    "cognitive sciences",
    "economic theory",
    "applied economics econometrics",
    "industrial relations",
    "business and management",
    "accounting",
    "finance",
    "general education",
    "special education",
    "sociology",
    "demography",
    "social topics",
    "anthropology ethnology",
    "law",
    "criminology penology",
    "political science",
    "public administration",
    "organisation theory",
    "cultural and economic geography",
    "urban studies",
    "transport planning and social aspects of transport",
    "environmental sciences social aspects",
    "journalism",
    "media and socio cultural communication",
    "information science social aspects",
    "library science",
    "other social sciences",
    "social sciences interdisciplinary",
    "history",
    "archaeology",
    "general language studies",
    "specific languages",
    "linguistics",
    "general literature studies",
    "literary theory",
    "specific literatures",
    "philosophy history and philosophy of science and technology",
    "ethics",
    "theology",
    "religious studies",
    "arts art history",
    "architectural design",
    "performing arts studies",
    "folklore studies",
    "studies on film radio and television",
]
